### ISSUE TITLE
sql injection vulnerablity in api.py

### ISSUE THREAD

**Issue by Ali4mini** [farzadoxo/todo-list#10]
use correct input validation and parametrized queries

**Comment by farzadoxo** [comment]
?

**Comment by farzadoxo** [comment]
whats problem?

**Comment by Ali4mini** [comment]
your code(api.py) is vulnerable to SQL Injection attacks.

**Comment by farzadoxo** [comment]
اخه کی میخواد به دیتابیس تودو لیست اتک بزنه :/

**Comment by Ali4mini** [comment]
better be safe than sorry :)
