### ISSUE TITLE
Docker runtime error

### ISSUE THREAD

**Issue by farzadoxo** [farzadoxo/todo-list#15]
[+] Building 2.8s (4/4) FINISHED                                 docker:default
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 749B                                       0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 547B                                       0.0s
 => ERROR [frontend internal] load metadata for docker.io/library/node:22  2.7s
 => CANCELED [backend internal] load metadata for docker.io/library/pytho  2.7s
------
 > [frontend internal] load metadata for docker.io/library/node:22-alpine:
------
failed to solve: node:22-alpine: failed to resolve source metadata for docker.io/library/node:22-alpine: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fnode%3Apull&service=registry.docker.io": remote error: tls: handshake failure

**Comment by Ali4mini** [comment]
you should login to your docker account with `docker login` commmand
