### ISSUE TITLE
broken endpoint

### ISSUE THREAD

**Issue by Ali4mini** [farzadoxo/todo-list#17]
@farzadoxo the task update returns 404 error.
the way i am calling it:  `PATCH /api/todos/3`

**Comment by farzadoxo** [comment]
3 is a task id right ?
dont send it to PATH parameter its a QUERY parameter .
PATCH /api/todos?id=3

**Comment by Ali4mini** [comment]
it shouldn't be a query parameter ( query parameters are usually used for filtering and sorting )
