### ISSUE TITLE
Sqlite3 Error

### ISSUE THREAD

**Issue by Ali4mini** [farzadoxo/todo-list#20]
there is an error happening in the back-end code but it doesnt break anything.
the error: 
`             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alireza/__projects__/todo-list/back-end/API/api.py", line 276, in all_todos
    items = DataBase.cursor.fetchall()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Recursive use of cursors not allowed.
`

**Comment by farzadoxo** [comment]
:/ why?
